services:
  - type: web
    name: bluwik-hms
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bluwik-hms-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py

databases:
  - name: bluwik-hms-db
    databaseName: bluwik_hms
    user: bluwik_hms_user 